services:
  api:
    image: upayanmazumder/learningdocker:latest
    build: .                           
    ports:
      - "3000:3000"                     
    environment:
      - NODE_ENV=production                                   
    restart: always                     
