name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t learningdocker:latest .

      # Push Docker image to local registry (or external Docker registry like DockerHub)
      - name: Push Docker image
        run: |
          docker tag learningdocker:latest upayanmazumder/learningdocker:latest
          docker push upayanmazumder/learningdocker:latest

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/your-deployment-name your-container-name=upayanmazumder/learningdocker:latest
