name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: upayanmazumder
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        id: build
        run: |
          TAG=learning-docker:$(date +%s)
          docker build . --file Dockerfile --tag upayanmazumder/$TAG
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Push the Docker image
        run: docker push upayanmazumder/$TAG
