name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to VPS
      run: |
        scp -r . <vps-user>@<vps-ip>:/home/<vps-user>/my-nodejs-app
        ssh <vps-user>@<vps-ip> 'cd /home/<vps-user>/my-nodejs-app && docker build -t my-nodejs-app . && docker stop $(docker ps -q) || true && docker run -d -p 5100:5100 my-nodejs-app'
